<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="System.Data.SQLite.EF6" Version="1.0.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../WaterFlow.Models/WaterFlow.Models.csproj" />
  </ItemGroup>
</Project>