<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="System.Data.SQLite.EF6" Version="1.0.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../WaterFlow.Models/WaterFlow.Models.csproj" />
    <ProjectReference Include="../WaterFlow.Data/WaterFlow.Data.csproj" />
    <ProjectReference Include="../WaterFlow.Services/WaterFlow.Services.csproj" />
  </ItemGroup>
</Project>