<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.1.1" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../WaterFlow.Models/WaterFlow.Models.csproj" />
    <ProjectReference Include="../WaterFlow.Data/WaterFlow.Data.csproj" />
  </ItemGroup>
</Project>